replicaCount: 1

image:
  repository: <your-username>/python-app
  pullPolicy: IfNotPresent
  tag: "1.0"

service:
  type: NodePort
  port: 5000

resources: {}

env:
  DEBUG: "true"
  ENVIRONMENT: "production"
